import os, json, argparse, random, warnings, gc, time
from pathlib import Path

import numpy as np
import tensorflow as tf
import deepxde as dde
import optuna
from sklearn.metrics import r2_score
from scipy.stats import pearsonr
from skimage.metrics import structural_similarity as ssim

warnings.filterwarnings("ignore")
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
optuna.logging.set_verbosity(optuna.logging.WARNING)
dde.config.set_default_float("float64")
dde.config.disable_xla_jit()

gpus = tf.config.list_physical_devices('GPU')
for gpu in gpus:
    try:
        tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError:
        pass

N_TRIALS    = 20
TUNE_ITERS  = 2_000
FULL_ITERS  = 15_000
WARMUP_ITERS = 5_000
LBFGS_ITERS = 5_000
N_OBS_PER_T = 100
N_DOMAIN    = 5_000
N_BOUNDARY  = 1_000
N_INITIAL   = 0
TUNE_N_DOMAIN   = 1_000
TUNE_N_BOUNDARY = 200
# Optuna trial budget split to mirror full training: warmup (lambda_pde=0) then physics.
# Ratio matches full schedule: WARMUP_ITERS/FULL_ITERS = 1/3.
TUNE_WARMUP_ITERS  = round(TUNE_ITERS * WARMUP_ITERS / FULL_ITERS)   # 667
TUNE_PHYSICS_ITERS = TUNE_ITERS - TUNE_WARMUP_ITERS                   # 1333

TRUE_SIZE = 5.0
S_MCS     = 60.0
H_MCS     = 1.0 / S_MCS

# ABM boundary geometry (from tester() in the ABM source).
# The ABM constrains u=0 (Dirichlet) on corner sub-regions:
#   facesBottom where X < boundaryat,  facesTop where X > nx-boundaryat
#   facesRight  where Y > ny-boundaryat, facesLeft where Y < boundaryat
# Remaining boundary faces use FiPy's natural zero-flux (Neumann) condition.
# boundaryat = nx / 10 for any grid size.
# In the PINN normalized domain [-1,1]×[-1,1]:
#   threshold = 2*(boundaryat/nx) - 1 = 2*(nx/10)/nx - 1 = -0.8 (grid-independent)
def corner_thresh(G):
    return 2.0 * (G / 10.0) / G - 1.0

CYTOKINE_NAMES = ["il8", "il1", "il6", "il10", "tnf", "tgf"]
MASK_E, MASK_NDN, MASK_NA, MASK_M1, MASK_M2 = 0, 1, 2, 3, 4


def set_seed(seed):
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed); np.random.seed(seed); tf.random.set_seed(seed)
    dde.config.set_random_seed(seed)

def compute_pde_params(G, cyt_idx):
    areaconv   = TRUE_SIZE**2 / G**2
    volumeconv = TRUE_SIZE**2 / G**2

    D_all = np.array([
        2.09e-6, 3.00e-7, 8.49e-8, 1.45e-8, 4.07e-9, 2.60e-7
    ]) * S_MCS / areaconv

    k_all = np.array([
        0.200, 0.600, 0.500, 0.500, 0.500 * 0.225, 0.500 / 25.0
    ]) * H_MCS

    sec = np.array([
        234e-5,    # [0] keil8
        1.46e-5,   # [1] kndnil8
        3.024e-5,  # [2] thetanail8
        225e-5,    # [3] knail1
        250e-5,    # [4] km1il6
        45e-5,     # [5] km2il10
        250e-5,    # [6] knatnf
        70e-5,     # [7] km1tnf
        280e-5,    # [8] km2tgf
    ]) * volumeconv * H_MCS

    return float(D_all[cyt_idx]), float(k_all[cyt_idx]), sec


def build_source_terms_1cyt(masks_dynamic, sec, cyt_idx, G, clip_max):
    # masks_dynamic: (T, G*G, 5) — one mask snapshot per training timestep
    T   = masks_dynamic.shape[0]
    n   = G * G
    me  = masks_dynamic[:, :, MASK_E]    # (T, G*G)
    mnn = masks_dynamic[:, :, MASK_NDN]
    mna = masks_dynamic[:, :, MASK_NA]
    mm1 = masks_dynamic[:, :, MASK_M1]
    mm2 = masks_dynamic[:, :, MASK_M2]
    z   = np.zeros((T, n), np.float64)

    # sec[5] = km2il10; ABM uses cellpresentm1 for IL-10 (matches ABM tester() source term)
    # NOTE: biologically this is an error (IL-10 is M2-secreted), but the training data
    # was generated by the ABM with this exact formulation. Fixing to mm2 here would make
    # the PINN enforce physics that contradict the data-generating process.
    s1_map = [sec[0]*me, sec[3]*mna, sec[4]*mm1, sec[5]*mm1, sec[6]*mna, sec[8]*mm2]
    s2_map = [sec[1]*mnn, z, z, z, sec[7]*mm1, z]
    e_map  = [sec[2]*mna, z, z, z, z, z]

    scale_factor = 2.0 / (clip_max + 1e-30)

    s1_arr = s1_map[cyt_idx].reshape(T, n, 1) * scale_factor
    s2_arr = s2_map[cyt_idx].reshape(T, n, 1) * scale_factor
    e_arr  = e_map[cyt_idx].reshape(T, n, 1)

    s1_tf = tf.constant(s1_arr, dtype=tf.float64)
    s2_tf = tf.constant(s2_arr, dtype=tf.float64)
    e_tf  = tf.constant(e_arr,  dtype=tf.float64)
    return s1_tf, s2_tf, e_tf


# PDE residual
def make_pde_1cyt(D, k, s1_tf, s2_tf, e_tf, G, T):
    # s1_tf, s2_tf, e_tf: (T, G*G, 1) — dynamic source terms per training timestep.
    # Collocation points outside the training window are clamped to index T-1.
    G_tf  = tf.constant(G, dtype=tf.float64)
    D_tf  = tf.constant([[D]], dtype=tf.float64)
    k_tf  = tf.constant([[k]], dtype=tf.float64)
    T_m1  = tf.constant(T - 1, dtype=tf.int32)

    def pde(x, y):
        d2x = dde.grad.hessian(y, x, i=0, j=0)
        d2y = dde.grad.hessian(y, x, i=1, j=1)
        ut  = dde.grad.jacobian(y, x, i=0, j=2)

        G_dyn = tf.cast(G_tf, tf.float64)
        ix = tf.cast(tf.clip_by_value(
            tf.floor((x[:, 0:1] + 1.0) / 2.0 * G_dyn),
            0.0, G_dyn - 1.0), tf.int32)
        iy = tf.cast(tf.clip_by_value(
            tf.floor((x[:, 1:2] + 1.0) / 2.0 * G_dyn),
            0.0, G_dyn - 1.0), tf.int32)
        # flat_idx = ix*G + iy matches Y_masks_pinn layout (see preprocessing.py comment).
        flat_idx = tf.squeeze(ix * tf.cast(G_tf, tf.int32) + iy, axis=1)

        # Map normalized time → M_pinn training index [0, T-1].
        # t_norm_all = linspace(-1,1,101): abs_t = round((t+1)/2*100), pinn_idx = abs_t-2.
        # Collocation points beyond the training window are clamped to T-1 (last training mask).
        t_norm_idx = tf.cast(tf.round((x[:, 2:3] + 1.0) / 2.0 * 100.0), tf.int32)
        pinn_idx   = tf.squeeze(tf.clip_by_value(t_norm_idx - 2, 0, T_m1), axis=1)

        gather_idx = tf.stack([pinn_idx, flat_idx], axis=1)
        s1_q = tf.gather_nd(s1_tf, gather_idx)
        s2_q = tf.gather_nd(s2_tf, gather_idx)
        e_q  = tf.gather_nd(e_tf,  gather_idx)

        # ∂u_scaled/∂t = D·Δu_s − k·(u_s+1) + s1_scaled + s2_scaled − e·(u_s+1)
        # The +1 offset arises from the affine normalization:
        #   u_phys = (u_scaled + 1) * clip_max / 2,  u_phys_min = 0
        # Omitting the constant terms −k and −e_q would introduce a systematic
        # residual bias equal to (k + e_q) at every collocation point.
        rhs = D_tf * (d2x + d2y) - k_tf * (y + 1.0) + s1_q + s2_q - e_q * (y + 1.0)
        return ut - rhs

    return pde

# metrics
def _fisher_z(r):
    r = np.clip(r, -0.9999, 0.9999)
    return 0.5 * np.log((1.0 + r) / (1.0 - r))

def _inv_fisher_z(z):
    return float(np.tanh(z))

def calculate_metrics(y_true, y_pred, masks, clip_max):
    T  = min(y_true.shape[0], y_pred.shape[0], masks.shape[0])
    yt = y_true[:T]; yp = np.maximum(y_pred[:T], 0.0)
    ms = np.max(masks[:T], axis=-1, keepdims=True)

    sq_diff = np.square(yt - yp)
    rmse = float(np.sqrt(np.sum(sq_diff * ms) / (np.sum(ms) + 1e-12)))
    unmasked_rmse = float(np.sqrt(np.mean(sq_diff)))
    r2   = float(r2_score(yt.flatten(), yp.flatten()))

    per_t_r2 = []
    for t in range(T):
        gt_f = yt[t].flatten(); pr_f = yp[t].flatten()
        per_t_r2.append(float(r2_score(gt_f, pr_f)) if np.std(gt_f) > 1e-12 else np.nan)

    dice_thr = 0.05 * clip_max if clip_max > 0 else 1e-9
    dices = []; n_empty = 0
    z_corrs = []
    ssims_v = []; n_ssim_skip = 0
    fixed_dr = float(clip_max) if clip_max > 0 else 1.0

    for t in range(T):
        gt = yt[t, :, :, 0]; pr = yp[t, :, :, 0]
        gb = (gt > dice_thr).astype(float); pb = (pr > dice_thr).astype(float)
        if np.sum(gb) + np.sum(pb) == 0:
            n_empty += 1
        else:
            dices.append((2.0 * np.sum(gb * pb)) / (np.sum(gb) + np.sum(pb) + 1e-12))
        if np.std(gt) > 1e-12 and np.std(pr) > 1e-12:
            r_val = float(pearsonr(gt.flatten(), pr.flatten())[0])
            if np.isfinite(r_val):
                z_corrs.append(_fisher_z(r_val))
        dr = float(np.max(gt) - np.min(gt))
        if dr > 1e-12:
            ssims_v.append(float(ssim(gt, pr, data_range=fixed_dr)))
        else:
            n_ssim_skip += 1

    return {
        "Global_R2":           r2,
        "Per_Timestep_R2":     per_t_r2,
        "Masked_RMSE":         rmse,
        "Unmasked_RMSE":       unmasked_rmse,
        "Avg_Dice":            float(np.mean(dices)) if dices else 0.0,
        "Dice_Empty_Skipped":  n_empty,
        "Spatial_Correlation": _inv_fisher_z(float(np.mean(z_corrs))) if z_corrs else 0.0,
        "SSIM":                float(np.mean(ssims_v)) if ssims_v else 0.0,
        "SSIM_Skipped_Frames": n_ssim_skip,
    }

def denormalize(x, clip_max):
    return (np.asarray(x, np.float64) + 1.0) / 2.0 * clip_max

def build_dde_model(G, hidden, n_layers, lr,
                    pde_fn, geomtime,
                    X_ic, Y_ic_obs,
                    X_obs, Y_obs,
                    lambda_pde=0.01, lambda_ic=1.0, lambda_bc=0.1,
                    num_domain=N_DOMAIN, num_boundary=N_BOUNDARY):
    # Mixed BC matching ABM tester():
    #   Dirichlet u=0 at corner sub-regions (bottom-left and top-right corners)
    #   Neumann ∂u/∂n=0 at remaining mid-edge boundary (FiPy natural condition)
    ct = corner_thresh(G)
    def on_dirichlet_corner(x, on_boundary):
        if not on_boundary:
            return False
        xc, yc = float(x[0]), float(x[1])
        if np.isclose(yc, -1.0, atol=1e-8) and xc < ct:   return True
        if np.isclose(yc,  1.0, atol=1e-8) and xc > -ct:  return True
        if np.isclose(xc,  1.0, atol=1e-8) and yc > -ct:  return True
        if np.isclose(xc, -1.0, atol=1e-8) and yc < ct:   return True
        return False

    def on_neumann_mid(x, on_boundary):
        return on_boundary and not on_dirichlet_corner(x, True)

    ic_bc  = dde.PointSetBC(X_ic, Y_ic_obs, component=0)
    dir_bc = dde.DirichletBC(geomtime,
                             lambda x: np.zeros((len(x), 1), np.float64),
                             on_dirichlet_corner, component=0)
    neu_bc = dde.NeumannBC(geomtime,
                           lambda x: np.zeros((len(x), 1), np.float64),
                           on_neumann_mid, component=0)
    obs_bc = dde.PointSetBC(X_obs, Y_obs, component=0)

    data = dde.data.TimePDE(
        geomtime, pde_fn,
        ic_bcs=[ic_bc, dir_bc, neu_bc, obs_bc],
        num_domain=num_domain,
        num_boundary=num_boundary,
        num_initial=N_INITIAL,
        train_distribution="uniform",
    )

    net = dde.maps.FNN(
        [3] + [hidden] * n_layers + [1],
        "tanh", "Glorot uniform"
    )
    net.apply_output_transform(lambda x, y: y)

    # loss order: [PDE, ic_bc, dir_bc, neu_bc, obs_bc]
    loss_weights = [lambda_pde, lambda_ic, lambda_bc, lambda_bc, 1.0]
    model = dde.Model(data, net)
    model.compile("adam", lr=lr, loss_weights=loss_weights)
    return model

def make_xy_grid(G):
    xs = np.linspace(-1.0, 1.0, G, dtype=np.float64)
    ys = np.linspace(-1.0, 1.0, G, dtype=np.float64)
    xx, yy = np.meshgrid(xs, ys, indexing="ij")
    return np.stack([xx.ravel(), yy.ravel()], axis=1)


def t_to_norm(t_idx, n_total=101):
    t_norm_all = np.linspace(-1.0, 1.0, n_total, dtype=np.float64)
    return float(t_norm_all[t_idx])

def make_objective(G, cyt_idx, pde_fn, geomtime,
                   X_ic, Y_ic_obs, X_obs_tr, Y_obs_tr,
                   Y_tgt_scaled, val_indices, seed):

    xy_grid = make_xy_grid(G)
    G2 = G * G

    def objective(trial):
        set_seed(seed)
        tf.keras.backend.clear_session()
        gc.collect()
        try:
            tf.config.experimental.reset_memory_stats('GPU:0')
        except Exception:
            pass

        hidden     = trial.suggest_categorical("hidden",        [50, 64, 128])
        n_layers   = trial.suggest_categorical("n_layers",      [3, 4])
        lr         = trial.suggest_float("learning_rate",       1e-4, 5e-3, log=True)
        lambda_pde = trial.suggest_float("lambda_pde",         1e-3, 1.0, log=True)
        lambda_ic  = trial.suggest_float("lambda_ic",          0.1,  10.0, log=True)
        lambda_bc  = trial.suggest_float("lambda_bc",          1e-3, 1.0, log=True)

        # Phase 1: data-only warmup — matches full training protocol (lambda_pde=0)
        model = build_dde_model(
            G, hidden, n_layers, lr,
            pde_fn, geomtime,
            X_ic, Y_ic_obs,
            X_obs_tr, Y_obs_tr,
            lambda_pde=0.0,
            lambda_ic=lambda_ic,
            lambda_bc=lambda_bc,
            num_domain=TUNE_N_DOMAIN,
            num_boundary=TUNE_N_BOUNDARY,
        )
        model.train(iterations=TUNE_WARMUP_ITERS, display_every=TUNE_ITERS + 1)

        # Phase 2: physics-informed — tune lambda_pde from data-fitted initialisation
        model.compile("adam", lr=lr,
                      loss_weights=[lambda_pde, lambda_ic, lambda_bc, lambda_bc, 1.0])
        model.train(iterations=TUNE_PHYSICS_ITERS, display_every=TUNE_ITERS + 1)

        mses = []
        for vi in val_indices:
            abs_t = vi + 2  
            tt  = np.full((G2, 1), t_to_norm(abs_t), np.float64)
            X_q = np.hstack([xy_grid, tt])
            Yp  = model.predict(X_q) 
            Yt  = Y_tgt_scaled[vi, :, :, cyt_idx].reshape(-1, 1).astype(np.float64)
            mses.append(float(np.mean((Yt - Yp) ** 2)))

        del model
        gc.collect()
        return float(np.mean(mses))

    return objective

def run_pipeline(grid, seed, cytokine):
    set_seed(seed)
    cyt_idx = CYTOKINE_NAMES.index(cytokine.lower())

    data_path = Path(f"./preprocessed/{grid}x{grid}") # preprocessing.py
    out_dir   = Path("./models/pinn"); out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n[{cytokine.upper()}] {grid}x{grid} — loading data...")

    Y_tgt  = np.load(data_path / "Y_target.npy").astype(np.float64)         # (99,G,G,6) scaled
    M_spat = np.load(data_path / "Y_masks_spatial.npy").astype(np.float64)   # (99,G,G,5)
    M_pinn = np.load(data_path / "Y_masks_pinn.npy").astype(np.float64)     # (99,G*G,5)
    Y_ic_full = np.load(data_path / "Y_ic.npy").astype(np.float64)          # (G,G,6) scaled

    with open(data_path / "metadata.json") as f:
        meta = json.load(f)
    clip_max = float(np.array(meta["scaling"]["max"])[cyt_idx])

    G2 = grid * grid
    N  = Y_tgt.shape[0]  # 99

    D, k, sec = compute_pde_params(grid, cyt_idx)

    s1_tf, s2_tf, e_tf = build_source_terms_1cyt(M_pinn[:70], sec, cyt_idx, grid, clip_max)
    pde_fn = make_pde_1cyt(D, k, s1_tf, s2_tf, e_tf, grid, T=70)

    t_norm_all = np.linspace(-1.0, 1.0, 101, dtype=np.float64)
    t_min = float(t_norm_all[2])   # first prediction timestep
    t_max = float(t_norm_all[-1])  # last timestep

    geom      = dde.geometry.Rectangle([-1.0, -1.0], [1.0, 1.0])
    timedomain = dde.geometry.TimeDomain(t_min, t_max)
    geomtime  = dde.geometry.GeometryXTime(geom, timedomain)

    xy_grid  = make_xy_grid(grid)
    tt0      = np.full((G2, 1), t_min, dtype=np.float64)
    X_ic     = np.hstack([xy_grid, tt0])
    Y_ic_obs = Y_ic_full[:, :, cyt_idx].reshape(G2, 1).astype(np.float64)  # scaled

    rng = np.random.default_rng(seed)
    val_indices   = list(range(70, 80))
    train_indices = list(range(70))

    # Consistent observation budget across grid resolutions.
    # PINN natively works with sparse observations — we keep ALL 70 training
    # timesteps but subsample spatial points per timestep to a fixed budget.
    # This ensures:
    #   - Same total observation count regardless of grid size → comparable results
    #   - Full temporal coverage (all 70 timesteps) → no information loss in time
    #   - Uniform random spatial coverage → unbiased spatial representation
    #
    # Budget: min(G², 2500) points per timestep (50×50 uses full grid as baseline)
    #   50×50   → 2,500 pts/t × 70 = 175,000 total (full grid, no subsampling)
    #   100×100 → 2,500 pts/t × 70 = 175,000 total (25% spatial subsampling)
    #   250×250 → 2,500 pts/t × 70 = 175,000 total (4% spatial subsampling)
    OBS_PTS_PER_T = min(G2, 2500)
    subsample = OBS_PTS_PER_T < G2

    X_obs_list = []; Y_obs_list = []
    for i in train_indices:
        abs_t = i + 2  # absolute timestep
        if subsample:
            idx_spatial = rng.choice(G2, size=OBS_PTS_PER_T, replace=False)
            xy_sub = xy_grid[idx_spatial]
            y_sub  = Y_tgt[i, :, :, cyt_idx].reshape(G2, 1).astype(np.float64)[idx_spatial]
        else:
            xy_sub = xy_grid
            y_sub  = Y_tgt[i, :, :, cyt_idx].reshape(G2, 1).astype(np.float64)

        t_obs = np.full((OBS_PTS_PER_T, 1), t_norm_all[abs_t], np.float64)
        X_obs_list.append(np.hstack([xy_sub, t_obs]))
        Y_obs_list.append(y_sub)

    X_obs_tr = np.vstack(X_obs_list)
    Y_obs_tr = np.vstack(Y_obs_list)

    print(f"  Train obs: {X_obs_tr.shape[0]:,} ({OBS_PTS_PER_T} pts/t × {len(train_indices)} timesteps"
          f"{', subsampled' if subsample else ', full grid'})")
    print(f"  IC points: {X_ic.shape[0]}  |  Grid: {grid}x{grid}={G2}  |  clip_max: {clip_max:.6f}")

    if seed == 42:
        print(f"Optuna: {N_TRIALS} trials x {TUNE_ITERS} iters...")
        study = optuna.create_study(
            direction="minimize",
            sampler=optuna.samplers.TPESampler(seed=42),
            pruner=optuna.pruners.MedianPruner(n_warmup_steps=3),
        )
        study.optimize(
            make_objective(
                grid, cyt_idx, pde_fn, geomtime,
                X_ic, Y_ic_obs,
                X_obs_tr, Y_obs_tr,
                Y_tgt,
                val_indices=val_indices,
                seed=42,
            ),
            n_trials=N_TRIALS, show_progress_bar=True, catch=(Exception,),
        )
        best = study.best_params
        optuna_val = float(study.best_value)
        print(f"  Best: {best}  |  val_loss = {optuna_val:.6f}")
    else:
        ref_path = out_dir / f"res_{cytokine}_{grid}_42.json"
        print(f"  Loading HP from {ref_path.name}")
        with open(ref_path) as f:
            ref = json.load(f)
        best = ref["best_params"]
        optuna_val = ref["optuna_best_val_loss"]

    tf.keras.backend.clear_session(); set_seed(seed)

    t_start = time.time()

    print(f"Phase 1: Data-only warmup ({WARMUP_ITERS} Adam, lambda_pde=0)...")
    model = build_dde_model(
        grid, best["hidden"], best["n_layers"], best["learning_rate"],
        pde_fn, geomtime,
        X_ic, Y_ic_obs,
        X_obs_tr, Y_obs_tr,
        lambda_pde=0.0,
        lambda_ic=best["lambda_ic"],
        lambda_bc=best["lambda_bc"],
    )
    model.train(iterations=WARMUP_ITERS, display_every=1000)

    PHYSICS_ITERS = FULL_ITERS - WARMUP_ITERS
    print(f"Phase 2: Physics-informed ({PHYSICS_ITERS} Adam, lambda_pde={best['lambda_pde']:.4f})...")
    model.compile("adam", lr=best["learning_rate"],
                   loss_weights=[best["lambda_pde"], best["lambda_ic"],
                                 best["lambda_bc"], best["lambda_bc"], 1.0])
    ckpt_path = str(out_dir / f"ckpt_{cytokine}_{grid}_{seed}")
    checker = dde.callbacks.ModelCheckpoint(
        ckpt_path, save_better_only=True, period=100,
    )
    model.train(iterations=PHYSICS_ITERS, display_every=2000, callbacks=[checker])

    print(f"Phase 3: L-BFGS polish ({LBFGS_ITERS} iters)...")
    dde.optimizers.set_LBFGS_options(maxiter=LBFGS_ITERS)
    model.compile("L-BFGS-B",
                   loss_weights=[best["lambda_pde"], best["lambda_ic"],
                                 best["lambda_bc"], best["lambda_bc"], 1.0])
    model.train(display_every=1000, callbacks=[checker])

    best_step = model.train_state.best_step
    import glob
    ckpt_files = sorted(glob.glob(ckpt_path + "*"))
    print(f"  Best step: {best_step}  |  Checkpoint files: {ckpt_files[:8]}")
    restore_path = None
    for suffix in [f"-{best_step}.ckpt", f"-{best_step}", ""]:
        candidate = ckpt_path + suffix
        if any(f.startswith(candidate) and (".index" in f or ".data-" in f) for f in ckpt_files):
            restore_path = candidate
            break
    if restore_path:
        print(f"  Restoring from: {restore_path}")
        model.restore(restore_path, verbose=1)
    else:
        print(f"WARNING: No checkpoint found for step {best_step}, using final weights.")

    print("Predicting full grid...")
    Yp_all = np.zeros((N, grid, grid, 1), dtype=np.float64)
    for i in range(N):
        abs_t = i + 2
        tt  = np.full((G2, 1), t_to_norm(abs_t), np.float64)
        X_q = np.hstack([xy_grid, tt])
        Yp_all[i, :, :, 0] = model.predict(X_q).reshape(grid, grid)

    Y_phys  = denormalize(Y_tgt[..., cyt_idx:cyt_idx + 1], clip_max)
    Yp_phys = denormalize(Yp_all, clip_max)

    suffix = f"{cytokine}_{grid}_{seed}"
    train_elapsed = time.time() - t_start
    print(f"  Training + prediction time: {train_elapsed:.1f}s")

    results = {
        "grid": grid, "seed": seed, "cytokine": cytokine,
        "best_params":          best,
        "optuna_best_val_loss": optuna_val,
        "train_time_seconds":   round(train_elapsed, 2),
        "results": {
            "Near_Horizon_t82_t91": calculate_metrics(
                Y_phys[80:90], Yp_phys[80:90], M_spat[80:90], clip_max),
            "Far_Horizon_t92_t100": calculate_metrics(
                Y_phys[90:99], Yp_phys[90:99], M_spat[90:99], clip_max),
        },
    }

    with open(out_dir / f"res_{suffix}.json", "w") as f:
        json.dump(results, f, indent=4)
    model.save(str(out_dir / f"weights_{suffix}"))
    print(f"Done! Saved: models/pinn/res_{suffix}.json")

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--grid",     type=int, required=True)
    ap.add_argument("--cytokine", type=str, required=True)
    ap.add_argument("--seed",     type=int, default=42)
    args = ap.parse_args()
    run_pipeline(args.grid, args.seed, args.cytokine)
