import os, json, argparse, random, warnings, gc
from pathlib import Path

import numpy as np
import tensorflow as tf
from sklearn.metrics import r2_score
from scipy.stats import pearsonr
from skimage.metrics import structural_similarity as ssim
import optuna

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
warnings.filterwarnings("ignore")
optuna.logging.set_verbosity(optuna.logging.WARNING)

N_TRIALS    = 20
TUNE_EPOCHS = 30
FULL_EPOCHS = 400

TRUE_SIZE   = 5.0
S_MCS       = 60.0
H_MCS       = 1.0 / S_MCS
CYTOKINE_NAMES = ["il8", "il1", "il6", "il10", "tnf", "tgf"]
MASK_E, MASK_NDN, MASK_NA, MASK_M1, MASK_M2 = 0, 1, 2, 3, 4

N_COLLOC         = 2000   # PDE collocation points per training step
N_BC             = 200    # boundary points for BC loss
N_PHYSICS_SAMPLES = 3     # branch inputs sampled per physics step (fix: was 1)
EVAL_CHUNK       = 4096


def set_seed(seed):
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed); np.random.seed(seed); tf.random.set_seed(seed)


# PDE 
def compute_pde_params(G, cyt_idx):
    areaconv   = TRUE_SIZE**2 / G**2
    volumeconv = TRUE_SIZE**2 / G**2
    D_all = np.array([
        2.09e-6, 3.00e-7, 8.49e-8, 1.45e-8, 4.07e-9, 2.60e-7
    ]) * S_MCS / areaconv
    k_all = np.array([
        0.200, 0.600, 0.500, 0.500, 0.500 * 0.225, 0.500 / 25.0
    ]) * H_MCS
    sec = np.array([
        234e-5, 1.46e-5, 3.024e-5, 225e-5, 250e-5,
        45e-5, 250e-5, 70e-5, 280e-5,
    ]) * volumeconv * H_MCS
    return float(D_all[cyt_idx]), float(k_all[cyt_idx]), sec


def build_source_arrays(masks_dynamic, sec, cyt_idx, G, clip_max):
    # masks_dynamic: (T, G*G, 5) — one mask snapshot per training timestep
    T   = masks_dynamic.shape[0]
    n   = G * G
    me  = masks_dynamic[:, :, MASK_E]    # (T, G*G)
    mnn = masks_dynamic[:, :, MASK_NDN]
    mna = masks_dynamic[:, :, MASK_NA]
    mm1 = masks_dynamic[:, :, MASK_M1]
    mm2 = masks_dynamic[:, :, MASK_M2]
    z   = np.zeros((T, n), np.float64)

    # sec[5] = km2il10; ABM uses cellpresentm1 for IL-10 (matches ABM source term)
    # NOTE: biologically this is an error (IL-10 is M2-secreted), but training data
    # was generated by the ABM with this exact formulation.
    s1_map = [sec[0]*me, sec[3]*mna, sec[4]*mm1, sec[5]*mm1, sec[6]*mna, sec[8]*mm2]
    s2_map = [sec[1]*mnn, z, z, z, sec[7]*mm1, z]
    e_map  = [sec[2]*mna, z, z, z, z, z]

    scale = 2.0 / (clip_max + 1e-30)
    s1 = s1_map[cyt_idx].reshape(T, n, 1) * scale
    s2 = s2_map[cyt_idx].reshape(T, n, 1) * scale
    e  = e_map[cyt_idx].reshape(T, n, 1)
    return (tf.constant(s1, tf.float32),
            tf.constant(s2, tf.float32),
            tf.constant(e,  tf.float32))


def corner_thresh(G):
    return 2.0 * (G / 10.0) / G - 1.0


class Branch(tf.keras.layers.Layer):
    def __init__(self, hidden, p, input_dim=7, **kw):
        super().__init__(**kw)
        self.fc1 = tf.keras.layers.Dense(hidden, activation="relu")
        self.fc2 = tf.keras.layers.Dense(hidden, activation="relu")
        self.fc3 = tf.keras.layers.Dense(p, activation="linear")

    def call(self, x, training=False):
        h = self.fc1(x)
        h = self.fc2(h)
        return self.fc3(h)


class Trunk(tf.keras.layers.Layer):
    def __init__(self, hidden, p, **kw):
        super().__init__(**kw)
        self.U   = tf.keras.layers.Dense(hidden, activation="tanh")
        self.V   = tf.keras.layers.Dense(hidden, activation="tanh")
        self.W1a = tf.keras.layers.Dense(hidden, activation="relu")
        self.W1b = tf.keras.layers.Dense(hidden, activation="linear")
        self.W2a = tf.keras.layers.Dense(hidden, activation="relu")
        self.W2b = tf.keras.layers.Dense(hidden, activation="linear")
        self.out = tf.keras.layers.Dense(p, activation="linear")

    def call(self, x):
        u = self.U(x); v = self.V(x)
        h = self.W1b(self.W1a(x)); h = h * u + (1.0 - h) * v
        h = self.W2b(self.W2a(h)); h = h * u + (1.0 - h) * v
        return self.out(h)


class PIDeepONet(tf.keras.Model):
    def __init__(self, hidden, p, branch_dim=7):
        super().__init__()
        self.branch = Branch(hidden, p, input_dim=branch_dim)
        self.trunk  = Trunk(hidden, p)
        self.bias   = self.add_weight(shape=(1,), initializer="zeros",
                                      trainable=True, name="bias")
        self._p = p

    def call_data(self, xb, xt, training=False):
        """
        Data forward pass.
        xb: (batch, D_branch) — branch input
        xt: (batch, n_pts, 3) — trunk input (x, y, t)
        Returns: (batch, n_pts, 1)
        """
        b = self.branch(xb, training=training)         # (batch, p)
        t = self.trunk(xt)                              # (batch, n_pts, p)
        r = tf.einsum("bp,bnp->bn", b, t) + self.bias  # (batch, n_pts)
        return tf.expand_dims(r, -1)                    # (batch, n_pts, 1)

    def call_physics_single(self, xb_single, xyt):
        b = self.branch(xb_single, training=True)       # (1, p)
        t = self.trunk(xyt)                              # (N_c, p)
        r = tf.reduce_sum(b[0] * t, axis=-1, keepdims=True) + self.bias
        return r                                         # (N_c, 1)

    def call(self, inputs, training=False):
        return self.call_data(inputs[0], inputs[1], training=training)

def build_branch_inputs(Xb, Xt, cyt_idx):
    N, _, G, _, _ = Xb.shape
    G2 = G * G

    f0 = Xb[:, 0, :, :, cyt_idx]  # (N, G, G) cytokine frame 0
    f1 = Xb[:, 1, :, :, cyt_idx]  # (N, G, G) cytokine frame 1

    masks = Xb[:, 0, :, :, 6:]     # (N, G, G, 5)
    mask_any = (masks.max(axis=-1) > 0.5).astype(np.float32)  # (N, G, G)

    xs = np.linspace(0, 1, G, dtype=np.float32)
    ys = np.linspace(0, 1, G, dtype=np.float32)
    xx, yy = np.meshgrid(xs, ys, indexing='ij')

    out = np.zeros((N, 15), dtype=np.float32)
    for i in range(N):
        ff0 = f0[i]; ff1 = f1[i]; m = mask_any[i]
        na = float(np.sum(m)) + 1e-6

        # Cytokine stats (rescale from [-1,1] to [0,1])
        out[i, 0] = (float(np.max(ff0)) + 1.0) / 2.0
        out[i, 1] = (float(np.mean(ff0)) + 1.0) / 2.0
        out[i, 2] = float(np.std(ff0))
        out[i, 3] = (float(np.max(ff1)) + 1.0) / 2.0
        out[i, 4] = (float(np.mean(ff1)) + 1.0) / 2.0
        out[i, 5] = float(np.std(ff1))

        # Cell geometry
        out[i, 6] = float(np.sum(xx * m) / na)   # centroid_x
        out[i, 7] = float(np.sum(yy * m) / na)   # centroid_y
        out[i, 8] = na / G2                        # extent

        # Per-type cell densities
        for ct in range(5):
            out[i, 9 + ct] = float(np.sum(masks[i, :, :, ct] > 0.5)) / G2

        # Time
        out[i, 14] = float(Xt[i, 0, 2])

    return out

def build_trunk_inputs(Xt):
    return Xt[:, :, :3].astype(np.float32)

def build_dataset(Xbranch, Xtrunk, Yf, batch_size, chunk_size, shuffle=True):
    N, n_pts, _ = Xtrunk.shape
    chunks = list(range(0, n_pts, chunk_size))
    d_branch = Xbranch.shape[1]

    def gen():
        order = np.arange(N)
        if shuffle:
            np.random.shuffle(order)
        for i in order:
            xb = Xbranch[i]
            for s in chunks:
                e = min(s + chunk_size, n_pts); size = e - s
                xt = Xtrunk[i, s:e]; y = Yf[i, s:e]
                if size < chunk_size:
                    pad = chunk_size - size
                    xt = np.concatenate([xt, np.zeros((pad, 3), np.float32)])
                    y  = np.concatenate([y,  np.zeros((pad, 1), np.float32)])
                sz = np.array([size], dtype=np.int32)
                yield (xb, xt, sz), y

    sig = (
        (tf.TensorSpec((d_branch,),       tf.float32),
         tf.TensorSpec((chunk_size, 3),   tf.float32),
         tf.TensorSpec((1,),              tf.int32)),
        tf.TensorSpec((chunk_size, 1),    tf.float32),
    )
    return (tf.data.Dataset.from_generator(gen, output_signature=sig)
            .batch(batch_size).prefetch(tf.data.AUTOTUNE))

def compute_pde_residual(model, xb_single, xyt, D, k, s1_tf, s2_tf, e_tf, G):
    # s1_tf, s2_tf, e_tf: (T, G*G, 1) — dynamic source terms per training timestep.
    # xyt: tf.constant watched by the enclosing GradientTape via nested tapes.
    G_f  = tf.constant(float(G), dtype=tf.float32)
    T_m1 = tf.constant(s1_tf.shape[0] - 1, dtype=tf.int32)

    with tf.GradientTape(persistent=True) as tape2:
        tape2.watch(xyt)
        with tf.GradientTape(persistent=True) as tape1:
            tape1.watch(xyt)
            u = model.call_physics_single(xb_single, xyt)  # (N_c, 1)

        du = tape1.gradient(u, xyt)       # (N_c, 3)
        u_x = du[:, 0:1]
        u_y = du[:, 1:2]
        u_t = du[:, 2:3]

    du_x_grad = tape2.gradient(u_x, xyt)  # (N_c, 3)
    du_y_grad = tape2.gradient(u_y, xyt)  # (N_c, 3)
    u_xx = du_x_grad[:, 0:1]
    u_yy = du_y_grad[:, 1:2]

    del tape1, tape2

    # Spatial index — flat_idx = ix*G + iy matches Y_masks_pinn layout
    ix = tf.cast(tf.clip_by_value(
        tf.floor((xyt[:, 0:1] + 1.0) / 2.0 * G_f), 0.0, G_f - 1.0), tf.int32)
    iy = tf.cast(tf.clip_by_value(
        tf.floor((xyt[:, 1:2] + 1.0) / 2.0 * G_f), 0.0, G_f - 1.0), tf.int32)
    flat_idx = tf.squeeze(ix * tf.cast(G_f, tf.int32) + iy, axis=1)

    # Time index: map normalized t → training mask index [0, T-1]
    t_norm_idx = tf.cast(tf.round((xyt[:, 2:3] + 1.0) / 2.0 * 100.0), tf.int32)
    pinn_idx   = tf.squeeze(tf.clip_by_value(t_norm_idx - 2, 0, T_m1), axis=1)

    gather_idx = tf.stack([pinn_idx, flat_idx], axis=1)
    s1_q = tf.gather_nd(s1_tf, gather_idx)
    s2_q = tf.gather_nd(s2_tf, gather_idx)
    e_q  = tf.gather_nd(e_tf,  gather_idx)

    # ∂u/∂t = D·Δu − k·(u+1) + s1 + s2 − e·(u+1)
    # The +1 offset arises from affine normalization: u_phys = (u_scaled+1)*clip_max/2
    rhs = D * (u_xx + u_yy) - k * (u + 1.0) + s1_q + s2_q - e_q * (u + 1.0)
    return u_t - rhs

def compute_bc_residual_mixed(model, xb_single, xyt_neu, xyt_dir):
    """
    Mixed BC matching ABM tester():
      Neumann  ∂u/∂n = 0 at mid-edge boundary points.
      Dirichlet u = 0   at corner sub-region points.
    """
    neu_res = tf.zeros((0,), tf.float32)
    if xyt_neu.shape[0] > 0:
        xyt_n = tf.constant(xyt_neu)
        with tf.GradientTape() as tape:
            tape.watch(xyt_n)
            u_n = model.call_physics_single(xb_single, xyt_n)
        du_n = tape.gradient(u_n, xyt_n)   # (N_neu, 3)
        x_c = xyt_neu[:, 0]; y_c = xyt_neu[:, 1]
        on_x = tf.cast(tf.abs(tf.abs(x_c) - 1.0) < 0.02, tf.float32)
        on_y = tf.cast(tf.abs(tf.abs(y_c) - 1.0) < 0.02, tf.float32)
        # Mid-edge points lie on exactly one face, so on_x and on_y don't both fire
        neu_res = du_n[:, 0] * on_x + du_n[:, 1] * on_y

    dir_res = tf.zeros((0,), tf.float32)
    if xyt_dir.shape[0] > 0:
        xyt_d = tf.constant(xyt_dir)
        u_d = model.call_physics_single(xb_single, xyt_d)
        dir_res = tf.squeeze(u_d, axis=1)

    return neu_res, dir_res

def sample_collocation(N_c, t_min, t_max):
    xy = np.random.uniform(-1.0, 1.0, (N_c, 2)).astype(np.float32)
    t  = np.random.uniform(t_min, t_max, (N_c, 1)).astype(np.float32)
    return np.hstack([xy, t])

def sample_boundary_mixed(N_bc, t_min, t_max, ct):
    """Sample boundary points split into Neumann (mid-edge) and Dirichlet (corners)."""
    pts = []
    n_per_side = N_bc // 4
    for _ in range(n_per_side):
        t = np.random.uniform(t_min, t_max)
        pts.append([-1.0, np.random.uniform(-1, 1), t])
        pts.append([ 1.0, np.random.uniform(-1, 1), t])
        pts.append([np.random.uniform(-1, 1), -1.0, t])
        pts.append([np.random.uniform(-1, 1),  1.0, t])
    pts = np.array(pts, dtype=np.float32)[:N_bc]
    x, y = pts[:, 0], pts[:, 1]
    is_dir = (
        ((np.abs(y + 1.0) < 0.02) & (x < ct))  |  # bottom-left
        ((np.abs(y - 1.0) < 0.02) & (x > -ct)) |  # top-right
        ((np.abs(x - 1.0) < 0.02) & (y > -ct)) |  # right-top
        ((np.abs(x + 1.0) < 0.02) & (y < ct))     # left-bottom
    )
    return pts[~is_dir], pts[is_dir]  # (xyt_neumann, xyt_dirichlet)

def masked_mse(pred, y, sz):
    idx  = tf.range(tf.shape(pred)[1])[tf.newaxis, :, tf.newaxis]
    mask = tf.cast(idx < tf.cast(sz[:, tf.newaxis, :], tf.int32), tf.float32)
    return tf.reduce_sum(tf.square(pred - y) * mask) / (tf.reduce_sum(mask) + 1e-8)

def train_step_data(model, opt, xb, xt, sz, y):
    with tf.GradientTape() as tape:
        loss = masked_mse(model.call_data(xb, xt, training=True), y, sz)
    opt.apply_gradients(zip(tape.gradient(loss, model.trainable_variables),
                            model.trainable_variables))
    return float(loss)

def train_step_physics(model, opt, xb_single, xyt_colloc, xyt_neu, xyt_dir,
                       D, k, s1_tf, s2_tf, e_tf, G,
                       lambda_pde, lambda_bc):

    xyt_c = tf.constant(xyt_colloc)

    with tf.GradientTape() as tape:
        residual = compute_pde_residual(
            model, xb_single, xyt_c, D, k, s1_tf, s2_tf, e_tf, G)
        loss_pde = lambda_pde * tf.reduce_mean(tf.square(residual))

        neu_res, dir_res = compute_bc_residual_mixed(model, xb_single, xyt_neu, xyt_dir)
        loss_bc_neu = tf.reduce_mean(tf.square(neu_res)) if tf.size(neu_res) > 0 else 0.0
        loss_bc_dir = tf.reduce_mean(tf.square(dir_res)) if tf.size(dir_res) > 0 else 0.0
        loss_bc = lambda_bc * (loss_bc_neu + loss_bc_dir)

        loss_total = loss_pde + loss_bc

    grads = tape.gradient(loss_total, model.trainable_variables)
    grads_and_vars = [(g, v) for g, v in zip(grads, model.trainable_variables)
                      if g is not None]
    if grads_and_vars:
        opt.apply_gradients(grads_and_vars)
    return float(loss_pde), float(loss_bc)


def val_mse(model, ds_vl):
    losses = []
    for batch in ds_vl:
        (xb, xt, sz), y = batch
        pred = model.call_data(xb, xt, training=False)
        losses.append(float(masked_mse(pred, y, sz)))
    return float(np.mean(losses))


def train_model(model, opt, ds_tr, ds_vl,
                Xbranch_tr, t_min, t_max, G, ct,
                D, k, s1_tf, s2_tf, e_tf,
                lambda_pde=0.01, lambda_bc=0.001,
                n_colloc=N_COLLOC, n_bc=N_BC,
                epochs=FULL_EPOCHS, patience=40, reduce_patience=15,
                min_lr=1e-7, verbose=True, physics_every=1):
    best_val = np.inf; best_w = None; wait = rw = 0
    N_tr = Xbranch_tr.shape[0]

    for ep in range(1, epochs + 1):
        # data loss 
        data_losses = []
        for batch in ds_tr:
            (xb, xt, sz), y = batch
            dl = train_step_data(model, opt, xb, xt, sz, y)
            data_losses.append(float(dl))
        tr_data = float(np.mean(data_losses))

        # physics loss — sample N_PHYSICS_SAMPLES branch inputs per step
        tr_pde = tr_bc = 0.0
        if lambda_pde > 0 and ep % physics_every == 0:
            xyt_c            = sample_collocation(n_colloc, t_min, t_max)
            xyt_neu, xyt_dir = sample_boundary_mixed(n_bc, t_min, t_max, ct)

            n_phys = min(N_PHYSICS_SAMPLES, N_tr)
            phys_idxs = np.random.choice(N_tr, size=n_phys, replace=False)
            pde_losses = []; bc_losses = []
            for pidx in phys_idxs:
                xb_s = tf.constant(Xbranch_tr[pidx:pidx+1])
                pde_l, bc_l = train_step_physics(
                    model, opt, xb_s, xyt_c, xyt_neu, xyt_dir,
                    D, k, s1_tf, s2_tf, e_tf, G,
                    lambda_pde, lambda_bc)
                pde_losses.append(pde_l); bc_losses.append(bc_l)
            tr_pde = float(np.mean(pde_losses))
            tr_bc  = float(np.mean(bc_losses))

        # val
        vl_mean = val_mse(model, ds_vl)

        if verbose and ep % 20 == 0:
            print(f"  Ep {ep:4d}  data={tr_data:.5f}  pde={tr_pde:.5f}  "
                  f"bc={tr_bc:.5f}  val={vl_mean:.5f}")

        if vl_mean < best_val:
            best_val = vl_mean; best_w = model.get_weights(); wait = rw = 0
        else:
            wait += 1; rw += 1

        if rw >= reduce_patience:
            lr = float(opt.learning_rate)
            new_lr = max(lr * 0.5, min_lr)
            if new_lr != lr:
                opt.learning_rate.assign(new_lr)
                if verbose: print(f"  LR → {new_lr:.2e}")
            rw = 0

        if wait >= patience:
            if verbose: print(f"  Early stop @ epoch {ep}")
            break

    if best_w:
        model.set_weights(best_w)
    return best_val


# eval
def predict_full(model, Xbranch, Xtrunk, chunk=EVAL_CHUNK):
    N, n_pts, _ = Xtrunk.shape
    out = np.zeros((N, n_pts, 1), np.float32)
    for i in range(N):
        xb = tf.constant(Xbranch[i:i+1])
        for s in range(0, n_pts, chunk):
            e = min(s + chunk, n_pts)
            xt = tf.constant(Xtrunk[i:i+1, s:e])
            out[i, s:e] = model.call_data(xb, xt, training=False).numpy()[0]
    return out


# metrics 
def _fisher_z(r):
    r = np.clip(r, -0.9999, 0.9999)
    return 0.5 * np.log((1.0 + r) / (1.0 - r))

def _inv_fisher_z(z):
    return float(np.tanh(z))

def calculate_metrics(y_true, y_pred, masks, clip_max):
    T = min(y_true.shape[0], y_pred.shape[0], masks.shape[0])
    yt = y_true[:T]; yp = np.maximum(y_pred[:T], 0.0)
    ms = np.max(masks[:T], axis=-1, keepdims=True)

    sq_diff = np.square(yt - yp)
    rmse = float(np.sqrt(np.sum(sq_diff * ms) / (np.sum(ms) + 1e-12)))
    unmasked_rmse = float(np.sqrt(np.mean(sq_diff)))
    r2   = float(r2_score(yt.flatten(), yp.flatten()))

    per_t_r2 = []
    for t in range(T):
        gt_f = yt[t].flatten(); pr_f = yp[t].flatten()
        per_t_r2.append(float(r2_score(gt_f, pr_f)) if np.std(gt_f) > 1e-12 else np.nan)

    dice_thr = 0.05 * clip_max if clip_max > 0 else 1e-9
    dices = []; n_empty = 0
    z_corrs = []
    ssims_v = []; n_ssim_skip = 0
    fixed_dr = float(clip_max) if clip_max > 0 else 1.0

    for t in range(T):
        gt = yt[t,:,:,0]; pr = yp[t,:,:,0]
        gb = (gt > dice_thr).astype(float); pb = (pr > dice_thr).astype(float)
        if np.sum(gb) + np.sum(pb) == 0:
            n_empty += 1
        else:
            dices.append((2.0 * np.sum(gb * pb)) / (np.sum(gb) + np.sum(pb) + 1e-12))
        if np.std(gt) > 1e-12 and np.std(pr) > 1e-12:
            r_val = float(pearsonr(gt.flatten(), pr.flatten())[0])
            if np.isfinite(r_val):
                z_corrs.append(_fisher_z(r_val))
        dr = float(np.max(gt) - np.min(gt))
        if dr > 1e-12:
            ssims_v.append(float(ssim(gt, pr, data_range=fixed_dr)))
        else:
            n_ssim_skip += 1

    return {
        "Global_R2":           r2,
        "Per_Timestep_R2":     per_t_r2,
        "Masked_RMSE":         rmse,
        "Unmasked_RMSE":       unmasked_rmse,
        "Avg_Dice":            float(np.mean(dices)) if dices else 0.0,
        "Dice_Empty_Skipped":  n_empty,
        "Spatial_Correlation": _inv_fisher_z(float(np.mean(z_corrs))) if z_corrs else 0.0,
        "SSIM":                float(np.mean(ssims_v)) if ssims_v else 0.0,
        "SSIM_Skipped_Frames": n_ssim_skip,
    }

def denormalize(x, clip_max):
    return (np.asarray(x, np.float64)+1.0)/2.0*clip_max

def make_objective(Xbr_tr, Xtr_tr, Yf_tr, Xbr_vl, Xtr_vl, Yf_vl,
                   t_min, t_max, G, ct, D, k, s1_tf, s2_tf, e_tf, seed):
    def objective(trial):
        set_seed(seed)
        tf.keras.backend.clear_session()
        p          = trial.suggest_categorical("p",          [64, 128, 256])
        hidden     = trial.suggest_categorical("hidden",     [128, 256])
        lr         = trial.suggest_float("learning_rate",    1e-5, 1e-3, log=True)
        bs         = trial.suggest_categorical("batch_size", [4, 8])
        chunk_size = trial.suggest_categorical("chunk_size", [2048, 4096])
        lambda_pde = trial.suggest_float("lambda_pde",      1e-4, 1.0, log=True)
        lambda_bc  = trial.suggest_float("lambda_bc",       1e-4, 0.1, log=True)

        ds_tr = build_dataset(Xbr_tr, Xtr_tr, Yf_tr, bs, chunk_size, shuffle=True)
        ds_vl = build_dataset(Xbr_vl, Xtr_vl, Yf_vl, bs, chunk_size, shuffle=False)

        d_branch = Xbr_tr.shape[1]
        model = PIDeepONet(hidden=hidden, p=p, branch_dim=d_branch)
        opt   = tf.keras.optimizers.Adam(lr)
        best  = train_model(
            model, opt, ds_tr, ds_vl,
            Xbr_tr, t_min, t_max, G, ct,
            D, k, s1_tf, s2_tf, e_tf,
            lambda_pde=lambda_pde, lambda_bc=lambda_bc,
            n_colloc=N_COLLOC, n_bc=N_BC,
            epochs=TUNE_EPOCHS, patience=8,
            reduce_patience=5, verbose=False,
            physics_every=2,
        )
        return float(best)
    return objective


def run_pipeline(grid, seed, cytokine):
    set_seed(seed)
    idx = CYTOKINE_NAMES.index(cytokine.lower())

    data_path = Path(f"./preprocessed/{grid}x{grid}")
    out_dir   = Path("./models/pi_deeponet"); out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n[{cytokine.upper()}] {grid}x{grid} — PI-DeepONet — loading data...")
    Xb = np.load(data_path/"X_branch.npy").astype(np.float32)
    Xt = np.load(data_path/"X_trunk.npy").astype(np.float32)
    Y  = np.load(data_path/"Y_target.npy").astype(np.float32)[..., idx:idx+1]
    M  = np.load(data_path/"Y_masks_spatial.npy").astype(np.float32)
    M_pinn = np.load(data_path/"Y_masks_pinn.npy").astype(np.float64)

    with open(data_path/"metadata.json") as f:
        meta = json.load(f)
    clip_max = float(meta["scaling"]["max"][idx])

    N = Xb.shape[0]; G2 = Xt.shape[1]; G = int(round(G2**0.5))
    Yf = Y.reshape(N, G2, 1)

    Xbranch = build_branch_inputs(Xb, Xt, idx)   # (N, 15)
    # Standardise using training-set statistics so all 15 features have zero mean
    # and unit variance — fixes inconsistent scaling between max/mean (rescaled to
    # [0,1]) and std features (left as raw normalized-field std, ~0–0.5).
    _tr_mean = Xbranch[:70].mean(axis=0, keepdims=True)
    _tr_std  = Xbranch[:70].std(axis=0, keepdims=True) + 1e-8
    Xbranch  = ((Xbranch - _tr_mean) / _tr_std).astype(np.float32)

    Xtrunk  = build_trunk_inputs(Xt)  # (N, G*G, 3)

    d_branch = Xbranch.shape[1]
    print(f"  Branch: (N, {d_branch})  |  Trunk: (N, {G2}, 3)  |  clip_max: {clip_max:.6f}")

    # PDE
    D, k, sec = compute_pde_params(grid, idx)
    ct = corner_thresh(grid)
    s1_tf, s2_tf, e_tf = build_source_arrays(M_pinn[:70], sec, idx, grid, clip_max)

    # time domain
    t_norm_all = np.linspace(-1.0, 1.0, 101, dtype=np.float32)
    t_min = float(t_norm_all[2])
    t_max = float(t_norm_all[-1])

    # 70/10/20
    Xbr_tr, Xtr_tr, Yf_tr = Xbranch[:70],   Xtrunk[:70],   Yf[:70]
    Xbr_vl, Xtr_vl, Yf_vl = Xbranch[70:80], Xtrunk[70:80], Yf[70:80]

    # optuna
    print(f"Optuna: {N_TRIALS} trials × {TUNE_EPOCHS} epochs...")
    study = optuna.create_study(
        direction="minimize",
        sampler=optuna.samplers.TPESampler(seed=seed),
        pruner=optuna.pruners.MedianPruner(n_warmup_steps=5),
    )
    study.optimize(
        make_objective(Xbr_tr, Xtr_tr, Yf_tr, Xbr_vl, Xtr_vl, Yf_vl,
                       t_min, t_max, G, ct, D, k, s1_tf, s2_tf, e_tf, seed),
        n_trials=N_TRIALS, show_progress_bar=True, catch=(Exception,),
    )
    best = study.best_params
    print(f"  Best: {best}  |  val_loss = {study.best_value:.6f}")

    # final training
    tf.keras.backend.clear_session(); set_seed(seed)
    ds_tr = build_dataset(Xbr_tr, Xtr_tr, Yf_tr,
                          best["batch_size"], best["chunk_size"], shuffle=True)
    ds_vl = build_dataset(Xbr_vl, Xtr_vl, Yf_vl,
                          best["batch_size"], best["chunk_size"], shuffle=False)

    model = PIDeepONet(hidden=best["hidden"], p=best["p"], branch_dim=d_branch)
    opt   = tf.keras.optimizers.Adam(best["learning_rate"])

    import time
    t_start = time.time()
    print(f"Final training (max {FULL_EPOCHS} epochs, "
          f"λ_pde={best['lambda_pde']:.4f}, λ_bc={best['lambda_bc']:.4f})...")
    train_model(
        model, opt, ds_tr, ds_vl,
        Xbr_tr, t_min, t_max, G, ct,
        D, k, s1_tf, s2_tf, e_tf,
        lambda_pde=best["lambda_pde"], lambda_bc=best["lambda_bc"],
        n_colloc=N_COLLOC, n_bc=N_BC,
        epochs=FULL_EPOCHS, patience=40, reduce_patience=15,
        verbose=True, physics_every=1,
    )
    train_elapsed = time.time() - t_start

    # unweighted PDE residual magnitude (no lambda scaling) across N_PHYSICS_SAMPLES
    # training inputs — verifies physics constraint is active, not numerically suppressed.
    xyt_eval = tf.constant(sample_collocation(N_COLLOC, t_min, t_max))
    _phys_idxs = np.random.choice(70, size=min(N_PHYSICS_SAMPLES, 70), replace=False)
    _pde_mags = []
    for _pi in _phys_idxs:
        _xb = tf.constant(Xbranch[_pi:_pi+1])
        _res = compute_pde_residual(model, _xb, xyt_eval, D, k, s1_tf, s2_tf, e_tf, G)
        _pde_mags.append(float(tf.reduce_mean(tf.square(_res)).numpy()))
    pde_residual_mag = float(np.mean(_pde_mags))

    # evaluate
    Yp_flat = predict_full(model, Xbranch, Xtrunk)
    Yp      = Yp_flat.reshape(N, G, G, 1)
    Y_phys  = denormalize(Y.reshape(N, G, G, 1), clip_max)
    Yp_phys = denormalize(Yp, clip_max)

    suffix  = f"{cytokine}_{grid}_{seed}"
    results = {
        "grid": grid, "seed": seed, "cytokine": cytokine,
        "best_params": best,
        "optuna_best_val_loss": float(study.best_value),
        "train_time_seconds":   round(train_elapsed, 2),
        "pde_residual_unweighted": pde_residual_mag,
        "results": {
            "Near_Horizon_t82_t91": calculate_metrics(
                Y_phys[80:90], Yp_phys[80:90], M[80:90], clip_max),
            "Far_Horizon_t92_t100": calculate_metrics(
                Y_phys[90:99], Yp_phys[90:99], M[90:99], clip_max),
        },
    }
    with open(out_dir/f"res_{suffix}.json", "w") as f:
        json.dump(results, f, indent=4)
    model.save_weights(out_dir/f"weights_{suffix}.weights.h5")
    print(f"DONE → models/pi_deeponet/res_{suffix}.json")

    for split, m in results["results"].items():
        print(f"  {split}: R²={m['Global_R2']:.4f}  RMSE={m['Masked_RMSE']:.6f}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--grid",     type=int, default=None)
    ap.add_argument("--cytokine", type=str, required=True)
    ap.add_argument("--seed",     type=int, default=42)
    args = ap.parse_args()

    if args.grid:
        run_pipeline(args.grid, args.seed, args.cytokine)
    else:
        for d in sorted(Path("./preprocessed").iterdir()):
            if d.is_dir():
                run_pipeline(int(d.name.split("x")[0]), args.seed, args.cytokine)

